version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
# don's sure about port
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/